name: budgetbuddy
description: A budget tracking application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8
  fl_chart: ^0.63.0
  flutter_local_notifications: ^17.0.0 # or latest
  image_picker: ^1.1.2
  intl: ^0.19.0
  timezone: ^0.9.3
  share_plus: ^10.0.2
  pdf: ^3.11.0



# Remove this (don't override if using a compatible version)
# dependency_overrides:
#   flutter_local_notifications: 14.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/g-logo.png
    - assets/app_logo.png
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21
